# Generated by Django 5.2 on 2025-05-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_pictures/'),
        ),
    ]
